### ISSUE TITLE
java.lang.IllegalArgumentException: requirement failed:  Region Actor not registered

### ISSUE THREAD

**Issue by sjoerdmulder** [akka/akka-persistence-cassandra#103]
Got this issue when a node was killed (probally because of thread-starvation). Only way i could fix it is a full cluster stop and drop the cassandra keyspace, which is not preferable but okay for now since we only use akka persistence for sharding.

Akka 2.4.6, akka-persistence-cassandra 0.12, Cassandra 3.0.5

Exception in receiveRecover when replaying event type [akka.cluster.sharding.ShardCoordinator$Internal$ShardHomeAllocated] with sequence number [54001] for persistenceId [/sharding/ProductCoordinator].

```
java.lang.IllegalArgumentException: requirement failed: Region Actor[akka.tcp://application@172.16.11.3:53583/system/sharding/Product#-375408820] not registered: State(Map(45 -> Actor[akka://application/system/sharding/Product#689991690], 34 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 67 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 93 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 12 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 66 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 89 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 51 -> Actor[akka://application/system/sharding/Product#689991690], 84 -> Actor[akka://application/system/sharding/Product#689991690], 73 -> Actor[akka://application/system/sharding/Product#689991690], 78 -> Actor[akka://application/system/sharding/Product#689991690], 19 -> Actor[akka://application/system/sharding/Product#689991690], 23 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 4 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 88 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 77 -> Actor[akka://application/system/sharding/Product#689991690], 15 -> Actor[akka://application/system/sharding/Product#689991690], 90 -> Actor[akka://application/system/sharding/Product#689991690], 44 -> Actor[akka://application/system/sharding/Product#689991690], 33 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 22 -> Actor[akka://application/system/sharding/Product#689991690], 56 -> Actor[akka://application/system/sharding/Product#689991690], 55 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 26 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 50 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 37 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 68 -> Actor[akka://application/system/sharding/Product#689991690], 13 -> Actor[akka://application/system/sharding/Product#689991690], 46 -> Actor[akka://application/system/sharding/Product#689991690], 24 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 94 -> Actor[akka://application/system/sharding/Product#689991690], 83 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 35 -> Actor[akka://application/system/sharding/Product#689991690], 16 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 79 -> Actor[akka://application/system/sharding/Product#689991690], 5 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 10 -> Actor[akka://application/system/sharding/Product#689991690], 59 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 87 -> Actor[akka://application/system/sharding/Product#689991690], 48 -> Actor[akka://application/system/sharding/Product#689991690], 21 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 76 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 54 -> Actor[akka://application/system/sharding/Product#689991690], 65 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 71 -> Actor[akka://application/system/sharding/Product#689991690], 32 -> Actor[akka://application/system/sharding/Product#689991690], 80 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 82 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 49 -> Actor[akka://application/system/sharding/Product#689991690], 6 -> Actor[akka://application/system/sharding/Product#689991690], 36 -> Actor[akka://application/system/sharding/Product#689991690], 1 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 17 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 25 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 60 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 47 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 31 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 69 -> Actor[akka://application/system/sharding/Product#689991690], 95 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 64 -> Actor[akka://application/system/sharding/Product#689991690], 53 -> Actor[akka://application/system/sharding/Product#689991690], 42 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 75 -> Actor[akka://application/system/sharding/Product#689991690], 0 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 20 -> Actor[akka://application/system/sharding/Product#689991690], 27 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 70 -> Actor[akka://application/system/sharding/Product#689991690], 2 -> Actor[akka://application/system/sharding/Product#689991690], 86 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 38 -> Actor[akka://application/system/sharding/Product#689991690], 81 -> Actor[akka://application/system/sharding/Product#689991690], 92 -> Actor[akka://application/system/sharding/Product#689991690], 18 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 7 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 29 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 41 -> Actor[akka://application/system/sharding/Product#689991690], 63 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 91 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970], 52 -> Actor[akka://application/system/sharding/Product#689991690], 85 -> Actor[akka://application/system/sharding/Product#689991690], 28 -> Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970]),Map(Actor[akka.tcp://application@172.16.10.3:58390/system/sharding/Product#-596355970] -> Vector(34, 67, 93, 12, 66, 89, 23, 4, 88, 33, 55, 26, 50, 37, 24, 83, 16, 5, 59, 21, 76, 65, 80, 82, 1, 17, 25, 60, 47, 31, 95, 42, 0, 27, 86, 18, 7, 29, 63, 91, 28), Actor[akka://application/system/sharding/Product#689991690] -> Vector(45, 51, 84, 73, 78, 19, 77, 15, 90, 44, 22, 56, 68, 13, 46, 94, 35, 79, 10, 87, 48, 54, 71, 32, 49, 6, 36, 69, 64, 53, 75, 20, 70, 2, 38, 81, 92, 41, 52, 85)),Set(Actor[akka.tcp://application@172.16.12.2:34712/system/sharding/Product#739142098], Actor[akka.tcp://application@172.16.9.2:59506/system/sharding/Product#-1272485012]),Set(),false)
    at scala.Predef$.require(Predef.scala:224)
    at akka.cluster.sharding.ShardCoordinator$Internal$State.updated(ShardCoordinator.scala:289)
    at akka.cluster.sharding.PersistentShardCoordinator$$anonfun$receiveRecover$1.applyOrElse(ShardCoordinator.scala:752)
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
    at akka.persistence.Eventsourced$$anon$3$$anonfun$1.applyOrElse(Eventsourced.scala:467)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:482)
    at akka.cluster.sharding.PersistentShardCoordinator.akka$persistence$Eventsourced$$super$aroundReceive(ShardCoordinator.scala:720)
    at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:511)
    at akka.persistence.Eventsourced$class.aroundReceive(Eventsourced.scala:176)
    at akka.cluster.sharding.PersistentShardCoordinator.aroundReceive(ShardCoordinator.scala:720)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:495)
    at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
```

I did however query for the event in cassandra, not sure this is usable.

```
cqlsh:akka> select * from messages where persistence_id = '/sharding/ProductCoordinator' AND partition_nr = 0 AND sequence_nr = 54001;       

 persistence_id               | partition_nr | sequence_nr | timestamp                            | timebucket | used | event                                                                                                                                                                | event_manifest | message | ser_id | ser_manifest | tag1 | tag2 | tag3 | writer_uuid
------------------------------+--------------+-------------+--------------------------------------+------------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+---------+--------+--------------+------+------+------+--------------------------------------
 /sharding/ProductCoordinator |            0 |       54001 | fefd61a0-2cb5-11e6-ab42-c7c25b8bbbc4 |   20160607 | True |       0x0a01381249616b6b612e7463703a2f2f6170706c69636174696f6e403137322e31362e362e343a35333839382f73797374656d2f7368617264696e672f50726f6475637423363839393931363930 |                |    null |     13 |           AF | null | null | null | 7442711a-5681-4486-8c79-8fb94f9b1795
 /sharding/ProductCoordinator |            0 |       54001 | 07c43cf0-2cb6-11e6-b3d0-c5656fbdf40b |   20160607 | True | 0x0a023336124b616b6b612e7463703a2f2f6170706c69636174696f6e403137322e31362e31312e333a35333538332f73797374656d2f7368617264696e672f50726f64756374232d333735343038383230 |                |    null |     13 |           AF | null | null | null | 3671fc9f-0708-449d-9740-60e25e68daae

(2 rows)
```

**Comment by patriknw** [comment]
@sjoerdmulder  You probably had a cluster split and got multiple writers to the same persistenceId. Are you using `auto-down`?

**Comment by sjoerdmulder** [comment]
Yes we are using auto-down.

**Comment by patriknw** [comment]
I strongly recommend against that. It doesn't handle network partitions. Use [Split Brain Resolver](http://doc.akka.io/docs/akka/rp-current/scala/split-brain-resolver.html), or similar.
