### ISSUE TITLE
Throws NullPointerException when replying SnapShot

### ISSUE THREAD

**Issue by GajendraNaidu** [akka/akka-persistence-cassandra#175]
When ActorSystem starting getting below exception. Could not make out any functionality loss. We are using AKKA Sharding as well. 

2017-03-27 22:23:17.196 [ERROR] [xxxxxxxxxxxxxxxx] [PersistentShardCoordinator] Persistence failure when replaying events for persistenceId [/sharding/reportCompute.interactionsCoordinator]. Last known sequence number [0]
java.lang.NullPointerException: null
	at akka.persistence.cassandra.snapshot.CassandraSnapshotStore$$anonfun$load1Async$2.apply(CassandraSnapshotStore.scala:107)
	at akka.persistence.cassandra.snapshot.CassandraSnapshotStore$$anonfun$load1Async$2.apply(CassandraSnapshotStore.scala:105)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)

**Comment by GajendraNaidu** [comment]
Plugin Version is 0.22 and AKKA version is 2.4.16

**Comment by dhpiggott** [comment]
Have you seen #164 (resolved in 0.24)? This sounds like it could be an instance of that (lack of actual functionality loss is consistent with my understanding of #164).

**Comment by GajendraNaidu** [comment]
I just see #164 . So this code change will allow NPE to be thrown but it will throw NoSuchElementException. I assume it will be caught and will not cause any functionality issues. 

https://github.com/akka/akka-persistence-cassandra/commit/82ad9934be06cacf521c46b0d79d5d2ad2bfb6bf

I guess I should close this issue.

**Comment by patriknw** [comment]
The NPE should not cause any trouble except scary logging. It should continue with next snapshot.

However, I see now that when there are no other snapshots to load it will fail the recovery. I'll fix this. Thanks for reporting.
