### ISSUE TITLE
failed: JournalPerfSpec on Travis

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#215]
JournalPerfSpec is failing rather frequently (but not deterministically) on Travis.

```
[info] A PersistentActor's performance
[info] - must measure: persistAsync()-ing 10000 events (18 seconds, 893 milliseconds)
[info]   + PersistAsync()-ing 10000 took 6695 ms 
[info]   + PersistAsync()-ing 10000 took 1445 ms 
[info]   + PersistAsync()-ing 10000 took 1855 ms 
[info]   + PersistAsync()-ing 10000 took 1350 ms 
[info]   + PersistAsync()-ing 10000 took 1206 ms 
[info]   + PersistAsync()-ing 10000 took 1219 ms 
[info]   + PersistAsync()-ing 10000 took 1511 ms 
[info]   + PersistAsync()-ing 10000 took 1655 ms 
[info]   + PersistAsync()-ing 10000 took 852 ms 
[info]   + PersistAsync()-ing 10000 took 1071 ms 
[info]   + Average time: 1886 ms 
[info] - must measure: persist()-ing 10000 events *** FAILED *** (20 seconds, 111 milliseconds)
[info]   java.lang.AssertionError: assertion failed: timeout (20 seconds) during expectMsg while waiting for 10000
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsg_internal(TestKit.scala:386)
[info]   at akka.testkit.TestKitBase$class.expectMsg(TestKit.scala:372)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:828)
[info]   at akka.persistence.journal.JournalPerfSpec.feedAndExpectLast(JournalPerfSpec.scala:87)
[info]   at akka.persistence.journal.JournalPerfSpec$$anonfun$1$$anonfun$apply$mcV$sp$3$$anonfun$apply$mcV$sp$4.apply$mcV$sp(JournalPerfSpec.scala:136)
[info]   at akka.persistence.journal.JournalPerfSpec.measure(JournalPerfSpec.scala:97)
[info]   at akka.persistence.journal.JournalPerfSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(JournalPerfSpec.scala:135)
```

**Comment by chbatey** [comment]
https://travis-ci.org/akka/akka-persistence-cassandra/jobs/318567847

**Comment by chbatey** [comment]
This is likely fixed by https://github.com/akka/akka-persistence-cassandra/pull/454 will re-open if we see it again
