### ISSUE TITLE
Do we need to change connection defaults in v2 compat mode?

### ISSUE THREAD

**Issue by ktoso** [akka/akka-persistence-cassandra#219]
It seems the default value of `new-connection-threshold-local = 800` exceeds what an V2 driver allows and could lead to:

```
java.lang.IllegalArgumentException: New connection threshold for LOCAL hosts must be in the range (0, 128)
	at com.datastax.driver.core.PoolingOptions.checkRequestsPerConnectionRange(PoolingOptions.java:622)
	at com.datastax.driver.core.PoolingOptions.setProtocolVersion(PoolingOptions.java:577)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1533)
	at com.datastax.driver.core.Cluster.init(Cluster.java:159)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
	at akka.persistence.cassandra.ConfigSessionProvider$$anonfun$connect$1.apply(ConfigSessionProvider.scala:48)
	at akka.persistence.cassandra.ConfigSessionProvider$$anonfun$connect$1.apply(ConfigSessionProvider.scala:42)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run$$original(Promise.scala:36)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:41)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

This was found on 0.52 but it seems we have the same currently.
Does this mean did not test with a local Cassandra 2 with that value I think?

More info here ( http://docs.datastax.com/en/developer/java-driver/3.3/manual/pooling/#simultaneous-requests-per-connection ):

> With protocol v2, there is no reason to throttle. It is set to 128 (the max) and you should not change it.
> With protocol v3, it is set to 1024 for LOCAL hosts, and 256 for REMOTE hosts. 

Do we need to change those defaults in `cassandra-2x-compat` perhaps?

**Comment by ktoso** [comment]
For reference, we had these values since 2015 https://github.com/akka/akka-persistence-cassandra/commit/f34cf8e0206ebb4c7a95940b523ddffd0eee5659 so it's a bit weird, if it seemingly does not work on V2, but back then pretty sure that V2 was the default and back then current cassandra hm

**Comment by ktoso** [comment]
Perhaps the check/failing was introduced in newer drivers

**Comment by johanandren** [comment]
Doesn't seem like the limit nor the checking has been changed in a long while: 
https://github.com/datastax/java-driver/blame/3.x/driver-core/src/main/java/com/datastax/driver/core/PoolingOptions.java#L614
https://github.com/datastax/java-driver/blame/3.x/driver-core/src/main/java/com/datastax/driver/core/StreamIdGenerator.java#L34

**Comment by chbatey** [comment]
2015 will have been a mixture of 2.0.* (v2 of native protocol) and 2.1.* (v3 of the native protocol - released in 2014)

The on the wire protocol for v2 uses a signed byte for the stream ID so 800 will never have worked.

https://github.com/apache/cassandra/blob/cassandra-2.0/doc/native_protocol_v2.spec#L131

I think we should just update the docs to be clear that you shouldn't be using a 2.0.* version of Cassandra or do we want to support it?
