### ISSUE TITLE
PersistentShardCoordinator - Persistence failure when replaying events for persistenceId InvalidQueryException: Undefined column name meta_ser_id

### ISSUE THREAD

**Issue by SeorasAshby** [akka/akka-persistence-cassandra#230]
Given Cassandra 3.10 tables created by akka-persistence-cassandra version 0.54 with akka cluster sharding version 2.5.4 with state-store-mode=persistence.

On upgrading from from version 0.54 to 0.55 akka sharding's PersistentShardCoordinator fails to replay state due to undefined column name meta_ser_id.

My understanding from the akka-persistence-cassandra 0.55 migration docs is that you should only need to add the new columns introduced on 0.55 if you need them. However it appears that PersistentShardCoordinator from akka 2.5.4 does not see the new columns as optional?

[warn] a.p.c.j.CassandraJournal - Failed to connect to Cassandra and initialize. It will be retried on demand. Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name meta_ser_id
[error] a.c.s.PersistentShardCoordinator - Persistence failure when replaying events for persistenceId [/sharding/RoqActorsCoordinator]. Last known sequence number [0]
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name meta_ser_id
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:435)
	at akka.persistence.cassandra.package$$anon$1$$anonfun$run$1.apply(package.scala:18)
	at scala.util.Try$.apply(Try.scala:192)
	at akka.persistence.cassandra.package$$anon$1.run(package.scala:18)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name meta_ser_id
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:148)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:179)
	at com.datastax.driver.core.RequestHandler.access$2400(RequestHandler.java:49)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:799)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:633)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1075)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:998)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)

**Comment by patriknw** [comment]
Thanks for reporting. The idea was indeed that they should be optional and I did some checks. Must have missed something. Will look into it. Use 0.54 until then.

**Comment by patriknw** [comment]
@SeorasAshby This was a puzzler. I tried (again) to run all tests against old table definitions, and that works (only failures were the tests that are actually testing the meta data).

Then I tried a Cluster Sharding example as you described, and then I can reproduce the issue. I tracked it down to that it fails when trying to create the materialized view even though the view already exists. It seems like "CREATE MATERIALIZED VIEW IF NOT EXISTS" fails even though it's not supposed to create the view since it already exists. I consider that to be a bug in Cassandra.

According to documentation it's supposed to work:
https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlCreateMaterializedView.html#cqlCreateMaterializedView__if-not-exists

Anyway, the workaround is simple. Run with the following when you already have existing data:
```
cassandra-journal.tables-autocreate = off
cassandra-snapshot-store.tables-autocreate = off 
```

In general I recommend using `off` for those anyway in production, and create the keyspace and tables manually (with script) once.

I don't think there is much we can do about this apart from documenting it in the migration guide.

**Comment by SeorasAshby** [comment]
@patriknw 

Thank you so much for investigating this and providing the workaround. I will give this a spin.

The recommendation for turning these settings off in production is really useful for me. I have been concerned about how Cassandra would behave with akka cluster when multiple akka cluster nodes try to adjust tables or even create keyspaces in the first place. The potential for races / conflict is my concern even though I think keyspace / table metadata is eventually consistent. Eliminating the possibility for conflict feels like a very good thing.

Best wishes

**Comment by SeorasAshby** [comment]
@patriknw Your workaround worked a treat and allowed my app to upgrade to version 0.55.

Thanks!
