### ISSUE TITLE
failed: CassandraSslSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#24]
When running tests after https://github.com/akka/akka-persistence-cassandra/pull/19 the CassandraSslSpec* fails on my machine (osx).

```
01/22 11:03:15 WARN [nioEventLoopGroup-2-3] i.n.c.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x7b68d077, /127.0.0.1:53524 => /127.0.0.1:53521]
java.lang.IllegalArgumentException: Cannot support TLS_RSA_WITH_AES_256_CBC_SHA with currently installed providers
	at sun.security.ssl.CipherSuiteList.<init>(CipherSuiteList.java:92) ~[na:1.8.0_45]
	at sun.security.ssl.SSLEngineImpl.setEnabledCipherSuites(SSLEngineImpl.java:2038) ~[na:1.8.0_45]
	at org.apache.cassandra.transport.Server$AbstractSecureIntializer.createSslHandler(Server.java:361) ~[cassandra-all-3.0.1.jar:3.0.1]
	at org.apache.cassandra.transport.Server$SecureInitializer.initChannel(Server.java:416) ~[cassandra-all-3.0.1.jar:3.0.1]
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:143) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:129) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) [netty-common-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.33.Final.jar:4.0.33.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.33.Final.jar:4.0.33.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by patriknw** [comment]
@magnusart do you know anything about this?

**Comment by magnusart** [comment]
@patriknw do you have JCE Java Cryptography Extensions installed? Looks like the US Export laws are the limiting factor. 

http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

**Comment by patriknw** [comment]
ok, but even if I install that and it works I think this can be too annoying for random contributors.
Is there a way to make the tests optional by checking if they are installed? I did a workaround here, but it checking the wrong thing: https://github.com/akka/akka-persistence-cassandra/commit/1614e4094b7b960ac708e4ed7c0fbfbcf2c12ff8

**Comment by magnusart** [comment]
Try this instead.

```
def checkForJCESupport:Boolean = {
  import javax.crypto._
  Cipher.getMaxAllowedKeyLength("AES") == Int.MaxValue
}
```
