### ISSUE TITLE
Failed: EventsByPersistenceIdWithControlSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#250]
Seems to be a flaky test

```
[info] EventsByPersistenceIdWithControlSpec:
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
10/12 11:17:27 ERROR[main] o.a.c.s.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
[info] Cassandra query EventsByPersistenceIdWithControl
[info] - must find new events *** FAILED *** (199 milliseconds)
[info]   A timeout occurred waiting for a future to complete. Queried 11 times, sleeping 15 milliseconds between each query. (EventsByPersistenceIdWithControlSpec.scala:78)
[info]   org.scalatest.concurrent.Futures$FutureConcept$$anon$1:
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.tryTryAgain$1(Futures.scala:538)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValueImpl(Futures.scala:550)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
[info]   at org.scalatest.concurrent.Futures$FutureConcept$class.futureValue(Futures.scala:476)
[info]   at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
[info]   at akka.persistence.cassandra.query.EventsByPersistenceIdWithControlSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(EventsByPersistenceIdWithControlSpec.scala:78)
[info]   at akka.persistence.cassandra.query.EventsByPersistenceIdWithControlSpec$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(EventsByPersistenceIdWithControlSpec.scala:73)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by chbatey** [comment]
Happened again: https://travis-ci.org/akka/akka-persistence-cassandra/jobs/290092223

**Comment by patriknw** [comment]
I'll take a look at this

**Comment by patriknw** [comment]
this was what I tried to fix in https://github.com/akka/akka-persistence-cassandra/pull/241
