### ISSUE TITLE
Failed: EventsByTagStageSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#278]
[DEBUG] [12/01/2017 12:01:10.473] [EventsByTagStageSpec-akka.actor.default-dispatcher-4] [EventsByTagStage(akka://EventsByTagStageSpec)] Nothing todo, waiting for next poll
[info] - must find missing first event in previous bucket *** FAILED *** (11 seconds, 58 milliseconds)
[0minfo]   java.lang.AssertionError: assertion failed: expected: message matching partial function but got unexpected message OnNext(EventEnvelope(TimeBasedUUID(4b9039a0-d68f-11e7-aee9-05d320b00e8f),p-1,2,e-2))
[info]   at scala.Predef$.assert(Predef.scala:170)
[info]   at akka.testkit.TestKitBase$class.expectMsgPF(TestKit.scala:420)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:882)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectEventWithTimeoutPF(StreamTestKit.scala:638)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextWithTimeoutPF(StreamTestKit.scala:615)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextPF(StreamTestKit.scala:607)
[info]   at akka.persistence.cassandra.query.EventsByTagStageSpec$$anonfun$2$$anonfun$apply$mcV$sp$20.apply(EventsByTagStageSpec.scala:495)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at akka.persistence.cassandra.query.EventsByTagStageSpec.withFixture(EventsByTagStageSpec.scala:62)
[info]   at org.scalatest.WordSpecLike$class.invokeWithFixture$1(WordSpecLike.scala:1075)
[info]   at org.scalatest.WordSpecLike$$anonfun$runTest$1.apply(WordSpecLike.s

**Comment by chbatey** [comment]
This is a test issue. The test, with bad luck on the timing, can end up writing the event two buckets ago rather than one

**Comment by chbatey** [comment]
Hopefully this is fixed by #279 closing for now
