### ISSUE TITLE
Failed: EventsByTagMigrationSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#292]
https://travis-ci.org/akka/akka-persistence-cassandra/jobs/313399259

This looks to have failed starting up cassandra before the test

```
[DEBUG] [12/08/2017 09:50:25.699] [EventsByTagMigration-akka.actor.default-dispatcher-9] [TimerScheduler(akka://EventsByTagMigration)] Cancel all timers
[DEBUG] [12/08/2017 09:50:25.699] [EventsByTagMigration-akka.actor.default-dispatcher-4] [TimerScheduler(akka://EventsByTagMigration)] Cancel all timers
[DEBUG] [12/08/2017 09:50:25.712] [EventsByTagMigration-akka.actor.default-dispatcher-15] [EventStream] shutting down: StandardOutLogger started
[DEBUG] [12/08/2017 09:50:28.181] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration-2)] logger log1-Logging$DefaultLogger started
[DEBUG] [12/08/2017 09:50:28.181] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration-2)] Default Loggers started
[DEBUG] [12/08/2017 09:50:28.204] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration-3)] logger log1-Logging$DefaultLogger started
[DEBUG] [12/08/2017 09:50:28.204] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration-3)] Default Loggers started
[DEBUG] [12/08/2017 09:50:28.218] [EventsByTagMigration-3-akka.actor.default-dispatcher-2] [EventStream] shutting down: StandardOutLogger started
[DEBUG] [12/08/2017 09:50:28.236] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration)] logger log1-Logging$DefaultLogger started
[DEBUG] [12/08/2017 09:50:28.236] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration)] Default Loggers started
[info] EventsByTagMigrationSpec:
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
12/08 09:50:29 ERROR[main] o.a.c.s.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
[DEBUG] [12/08/2017 09:50:33.381] [EventsByTagMigration-akka.actor.default-dispatcher-7] [akka.persistence.Persistence(akka://EventsByTagMigration)] Create plugin: cassandra-journal akka.persistence.cassandra.journal.CassandraJournal
[DEBUG] [12/08/2017 09:50:33.381] [EventsByTagMigration-akka.actor.default-dispatcher-7] [akka.persistence.Persistence(akka://EventsByTagMigration)] Create plugin: cassandra-snapshot-store akka.persistence.cassandra.snapshot.CassandraSnapshotStore
[DEBUG] [12/08/2017 09:50:35.336] [pool-5-thread-4] [akka.actor.ActorSystemImpl(EventsByTagMigration)] awaitPersistenceInit took 1956 ms EventsByTagMigration
[DEBUG] [12/08/2017 09:50:35.336] [pool-5-thread-4] [akka.actor.ActorSystemImpl(EventsByTagMigration)] Creating old tables
[DEBUG] [12/08/2017 09:50:57.205] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration-2)] logger log1-Logging$DefaultLogger started
[DEBUG] [12/08/2017 09:50:57.205] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration-2)] Default Loggers started
[DEBUG] [12/08/2017 09:50:57.213] [EventsByTagMigration-2-akka.actor.default-dispatcher-5] [EventStream] shutting down: StandardOutLogger started
[DEBUG] [12/08/2017 09:50:57.224] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration-3)] logger log1-Logging$DefaultLogger started
[DEBUG] [12/08/2017 09:50:57.224] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration-3)] Default Loggers started
[DEBUG] [12/08/2017 09:50:57.231] [EventsByTagMigration-3-akka.actor.default-dispatcher-6] [EventStream] shutting down: StandardOutLogger started
[info] akka.persistence.cassandra.EventsByTagMigrationSpec *** ABORTED *** (28 seconds, 988 milliseconds)
[info]   com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:39001] Timed out waiting for server response
[info]   at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:44)
[info]   at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:26)
[info]   at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
[info]   at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
[info]   at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
[info]   at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:43)
[info]   at akka.persistence.cassandra.AbstractEventsByTagMigrationSpec.beforeAll(EventsByTagMigrationSpec.scala:358)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.persistence.cassandra.AbstractEventsByTagMigrationSpec.run(EventsByTagMigrationSpec.scala:320)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
[info]   at sbt.TestFunction.apply(TestFramework.scala:207)
[info]   at sbt.Tests$.sbt$Tests$$processRunnable$1(Tests.scala:239)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:245)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:63)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info]   at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
[info]   at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info]   at sbt.Execute.work(Execute.scala:235)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info]   at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
[info]   at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[info]   Cause: com.datastax.driver.core.exceptions.OperationTimedOutException: [localhost/127.0.0.1:39001] Timed out waiting for server response
[info]   at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:772)
[info]   at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1380)
[info]   at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:625)
[info]   at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:700)
[info]   at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:428)
[info]   at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
[info]   at java.lang.Thread.run(Thread.java:748)
[DEBUG] [12/08/2017 09:50:57.328] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration)] logger log1-Logging$DefaultLogger started
[DEBUG] [12/08/2017 09:50:57.328] [pool-5-thread-4] [EventStream(akka://EventsByTagMigration)] Default Loggers started
```

**Comment by chbatey** [comment]
Fixed by https://github.com/akka/akka-persistence-cassandra/pull/454
