### ISSUE TITLE
InstanceAlreadyExistsException Unable to register counter

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#294]
Nothing critical but we should try to make the jmx metrics names unique.

```
[info] 09:41:26.361 [MultiDcSystem-cassandra-plugin-default-dispatcher-21] DEBUG c.c.m.JmxReporter - Unable to register counter
[info] javax.management.InstanceAlreadyExistsException: MultiDcSystem-metrics:name=ignores-on-client-timeout
[info] 	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
[info] 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
[info] 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
[info] 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
[info] 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
[info] 	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
[info] 	at com.codahale.metrics.JmxReporter$JmxListener.registerMBean(JmxReporter.java:505)
[info] 	at com.codahale.metrics.JmxReporter$JmxListener.onCounterAdded(JmxReporter.java:556)
[info] 	at com.codahale.metrics.MetricRegistry.notifyListenerOfAddedMetric(MetricRegistry.java:350)
[info] 	at com.codahale.metrics.MetricRegistry.addListener(MetricRegistry.java:191)
[info] 	at com.codahale.metrics.JmxReporter.start(JmxReporter.java:715)
[info] 	at com.datastax.driver.core.Metrics.<init>(Metrics.java:104)
[info] 	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1448)
[info] 	at com.datastax.driver.core.Cluster.init(Cluster.java:159)
[info] 	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
[info] 	at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:305)
[info] 	at akka.persistence.cassandra.ConfigSessionProvider$$anonfun$connect$1.apply(ConfigSessionProvider.scala:49)
[info] 	at akka.persistence.cassandra.ConfigSessionProvider$$anonfun$connect$1.apply(ConfigSessionProvider.scala:43)
```

**Comment by chbatey** [comment]
Was this running multiple in the same JVM?

**Comment by patriknw** [comment]
It was the apps sampl, ec2 testing. So only one ActorSystem per jvm.
