### ISSUE TITLE
EventsByPersistenceIdStage: Previous query was not exhausted

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#295]
version: 0.80-RC2

```
16:08:22.315 ERROR [akka.actor.RepointableActorRef] [MultiDcSystem-cassandra-plugin-default-dispatcher-21] - Error in stage [akka.persistence.cassandra.query.EventsByPersistenceIdStage@3f402c4e]: Previous query was not exhausted
java.lang.IllegalStateException: Previous query was not exhausted
        at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.query(EventsByPersistenceIdStage.scala:340)
        at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.akka$persistence$cassandra$query$EventsByPersistenceIdStage$$anon$$tryPushOne(EventsByPersistenceIdStage.scala:440)
        at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.onPull(EventsByPersistenceIdStage.scala:364)
```

I have full debug logs if needed.

**Comment by chbatey** [comment]
Looking at the code I can see this happening when we go into looking for missing mode, can you send me logs to confirm?

**Comment by patriknw** [comment]
Here is the log. Including 10000 lines before the error.
[log13_exhausted.txt.gz](https://github.com/akka/akka-persistence-cassandra/files/1564737/log13_exhausted.txt.gz)
