### ISSUE TITLE
EventsByPersistenceIdStage: Query already in progress

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#299]
I forgot to delete snapshots but deleted all messages. Not sure if that is related, but got this:
```
java.lang.IllegalStateException: Query already in progress
--
	at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.query(EventsByPersistenceIdStage.scala:338)
	at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.lookForMissingSeqNr(EventsByPersistenceIdStage.scala:330)
	at akka.persistence.cassandra.query.EventsByPersistenceIdStage$$anon$1.onTimer(EventsByPersistenceIdStage.scala:309)
	at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1452)
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1441)
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1441)
```

[log22_inprogress.txt.gz](https://github.com/akka/akka-persistence-cassandra/files/1575216/log22_inprogress.txt.gz)

**Comment by chbatey** [comment]
Different to the last one, but similar, it is when we go via the timer and we've given up the last time looking for missing. I failed at  making a test that deterministically fails
