### ISSUE TITLE
Undefined column name tags

### ISSUE THREAD

**Issue by ikr0m** [akka/akka-persistence-cassandra#328]
I've following error:
```
Failed to persist event type [SomeCmd] with sequence number [1] for persistenceId [some_persistence_id].
java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name tags
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:502)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:461)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
        at akka.persistence.cassandra.package$ListenableFutureConverter$$anon$2.$anonfun$run$2(package.scala:39)
        at scala.util.Try$.apply(Try.scala:209)
        at akka.persistence.cassandra.package$ListenableFutureConverter$$anon$2.run(package.scala:39)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Undefined column name tags
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:148)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:220)
        at com.datastax.driver.core.SessionManager$4.apply(SessionManager.java:196)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:221)
        at com.google.common.util.concurrent.AbstractTransformFuture$AsyncTransformFuture.doTransform(AbstractTransformFuture.java:210)
        at com.google.common.util.concurrent.AbstractTransformFuture.run(AbstractTransformFuture.java:130)
        at com.google.common.util.concurrent.MoreExecutors$5$1.run(MoreExecutors.java:952)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
```
I'm using scala 2.12, akka 2.5.8, playframework 2.6.11. Dependencies.scala contains:
```
"com.typesafe.akka" %% "akka-persistence-cassandra" % "0.58",
"com.typesafe.akka" %% "akka-persistence-cassandra-launcher" % "0.58" % Test,
```

I suspect that it happened after I tried with `akka-persistence-cassandra v0.82` yesterday. So, I had been using v0.58, then tried with v0.82, worked for a while, then started using v0.58 again.

**Comment by ikr0m** [comment]
I've run following code as described in migration guide and then error disappeared:
```
  val migrator = EventsByTagMigration(context.system)
  val schemaMigration: Future[Done] = for {
    _ <- migrator.createTables()
    done <- migrator.addTagsColumn().recover { case i: ExecutionException if i.getMessage.contains("conflicts with an existing column") => Done}
  } yield done
```
Interesting part that the issue happened in v0.58. Maybe because I've created events/snapshots/persistenceIds when I was testing v0.82. Now I'm using v0.58.
This issue can be closed.

**Comment by patriknw** [comment]
Note that if you use auto-create tables that will only create the new table definitions if there is no existing table, i.e. you have to drop the tables or keyspace to re-create new tables. In production you would use alter table to not loose data. I think `EventsByTagMigration` class adds the columns when migrating to 0.80+
https://github.com/akka/akka-persistence-cassandra#migrations-to-080-and-later
