### ISSUE TITLE
Failed: EventsByTag

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#344]
```
[info] Current EventsByTag
[info] - must find new events (550 milliseconds)
[info] - must empty tag completes (40 milliseconds)
[info] - must find events - paging *** FAILED *** (129 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected: message matching partial function but got unexpected message OnComplete
[info]   at scala.Predef$.assert(Predef.scala:219)
[info]   at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:420)
[info]   at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:416)
[info]   at akka.testkit.TestKit.expectMsgPF(TestKit.scala:890)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectEventWithTimeoutPF(StreamTestKit.scala:638)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextWithTimeoutPF(StreamTestKit.scala:615)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextPF(StreamTestKit.scala:607)
[info]   at akka.persistence.cassandra.query.EventsByTagStageSpec.$anonfun$new$6(EventsByTagStageSpec.scala:152)
[info]   at scala.runtime.java8.JFunction1$mcVJ$sp.apply(JFunction1$mcVJ$sp.java:12)
[info]   at scala.collection.immutable.NumericRange.foreach(NumericRange.scala:71)
[info]   at akka.persistence.cassandra.query.EventsByTagStageSpec.$anonfun$new$4(EventsByTagStageSpec.scala:150)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.persistence.cassandra.query.EventsByTagStageSpec.withFixture(EventsByTagStageSpec.scala:64)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEn
```

https://travis-ci.org/akka/akka-persistence-cassandra/jobs/359741479

**Comment by chbatey** [comment]
Likely fixed by https://github.com/akka/akka-persistence-cassandra/pull/454
