### ISSUE TITLE
compatibility issue with Cassandra 2.1.9 (protocol v3)

### ISSUE THREAD

**Issue by atamborrino** [akka/akka-persistence-cassandra#35]
Hi,

We just updated akka-persistence-cassandra from 0.6 to 0.7. We are using Akka Cluster Sharding in our project. We are using Cassandra 2.2.x.

Persistence-cassandra + Sharding worked smoothly with 0.6, but with 0.7 we have the following error when the TaskManagerCoordinator tries to persist a ShardRegionRegistered event:
```
2016-01-26 09:47:16,572 ERROR [akka.cluster.sharding.PersistentShardCoordinator] (kairos-akka.actor.default-dispatcher-19) Failed to persist event type [akka.cluster.sharding.ShardCoordinator$Internal$ShardRegionRegistered] with sequence number [1] for persistenceId [/sharding/TaskManagerCoordinator].
java.lang.IllegalStateException: Unset value at index 5. If you want this value to be null, please set it to null explicitly.
	at com.datastax.driver.core.BoundStatement.ensureAllSet(BoundStatement.java:1351)
	at com.datastax.driver.core.SessionManager.makeRequestMessage(SessionManager.java:559)
	at com.datastax.driver.core.SessionManager.executeAsync(SessionManager.java:128)
	at akka.persistence.cassandra.journal.CassandraJournal.akka$persistence$cassandra$journal$CassandraJournal$$execute(CassandraJournal.scala:267)
	at akka.persistence.cassandra.journal.CassandraJournal$$anonfun$5.apply(CassandraJournal.scala:140)
	at akka.persistence.cassandra.journal.CassandraJournal$$anonfun$5.apply(CassandraJournal.scala:137)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.immutable.List.map(List.scala:285)
	at akka.persistence.cassandra.journal.CassandraJournal.asyncWriteMessages(CassandraJournal.scala:137)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1$$anonfun$liftedTree1$1$1.apply(AsyncWriteJournal.scala:66)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1$$anonfun$liftedTree1$1$1.apply(AsyncWriteJournal.scala:66)
	at akka.pattern.CircuitBreaker$State$class.materialize$1(CircuitBreaker.scala:298)
	at akka.pattern.CircuitBreaker$State$class.callThrough(CircuitBreaker.scala:315)
	at akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:363)
	at akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:371)
	at akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:115)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1.liftedTree1$1(AsyncWriteJournal.scala:66)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$1.applyOrElse(AsyncWriteJournal.scala:66)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
	at akka.persistence.cassandra.journal.CassandraJournal.aroundReceive(CassandraJournal.scala:31)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by patriknw** [comment]
Have you migrated the schema? See https://github.com/akka/akka-persistence-cassandra#migrations-from-06-to-07
Also note the `cassandra-2x-compat` setting, as explained in README.

**Comment by atamborrino** [comment]
Yes we have followed the README: drop old event and snapshot keyspaces (to test with clean data) and put ```cassandra-journal.cassandra-2x-compat=on``` 

From the error and the concerned code https://github.com/akka/akka-persistence-cassandra/blob/master/src/main/scala/akka/persistence/cassandra/journal/CassandraJournal.scala#L207, it seems that if there is no tag, the Cassandra "tag" statements are not bound, hence the "Unset value at index 5" that corresponds to the first tag column. 

It seems that they should be bound to "null" if there is no tag, is it not?

**Comment by patriknw** [comment]
Looks like you are right. Hmm, we have plenty of tests that store events that are not tagged, so I can't understand why they don't detect this. I'll look a bit at this tomorrow and release a patch.
Thanks for reporting.

**Comment by patriknw** [comment]
I found the reason, L558 in SessionManager:
```
            if (protocolVersion.compareTo(ProtocolVersion.V4) < 0)
                bs.ensureAllSet();
```

so it's not mandatory use null for v4 of the protocol, but when using C* 2.2 the protocol is v3

**Comment by patriknw** [comment]
but according to the source code of ProtocolVersion and https://datastax.github.io/java-driver/features/native_protocol/ V4 should be supported by 2.2.0 or later. Exactly which Cassandra version are you using?

**Comment by patriknw** [comment]
When I ran tests against a 2.2.4 server I did not see this issue.

**Comment by atamborrino** [comment]
You're right, our test env stack use Cassandra 2.1.9. But according to the README it should be supported, so I think we can put null values when there is not tag for all Cassandra version.

**Comment by atamborrino** [comment]
Do you have time to fix the issue or do you want me to do a PR?

**Comment by patriknw** [comment]
@atamborrino I have fixed it: https://github.com/akka/akka-persistence-cassandra/pull/36

**Comment by atamborrino** [comment]
Thanks, I'll be waiting for a published patched version :)

**Comment by atamborrino** [comment]
Any chance to have a published patched 0.7.1 version ? We can not use 0.9-snapshot yet because we are using a lib that depends on akka-stream 2.0 that is not binary compatible with Akka 2.4.2-RC1.

**Comment by patriknw** [comment]
but 0.7 was not for akka-stream 2.0, it was using akka-stream 1.0

**Comment by atamborrino** [comment]
Ah yes you're right, we missed that. We'll stay on 0.6 for cassandra 2.x for now (which has no deps on akka-stream) and then we'll do the schema migration later on to 0.8+.

Thanks for your help ;)

**Comment by patriknw** [comment]
sounds good, thanks
