### ISSUE TITLE
Backward compatible class field serializer/serialization issue

### ISSUE THREAD

**Issue by ikr0m** [akka/akka-persistence-cassandra#360]
Until I started using akka-persistence, I used akka-kryo-serialization https://github.com/romix/akka-kryo-serialization. Then I started using akka-persistence with akka-persistence-cassandra. Everything worked fine. 
But when I added new field to my case class which was persisted to cassandra, recovering snapshot failed. Below is error log:
```
2018-06-26 14:47:37,191 [warn] a.p.c.s.CassandraSnapshotStore - Failed to load snapshot [SnapshotMetadata(Persistence_Id_XXX,140,1530005815495)] (3 of 3), last attempt. Caused by: [com.esotericsoftware.kryo.KryoException: Unable to find class: ello! How are you? What can I do for you today?
Serialization trace:
tdate1 (com.app.AppProtocol$CustomMessage)
customMessages (com.app.AppProtocol$CustomChat)
chats (com.app.AppProtocol$CustomChatDataState)]
2018-06-26 14:47:37,210 [error] c.a.a.a.c.d.CustomChatManager - Persistence failure when replaying events for persistenceId [Persistence_Id_XXX]. Last known sequence number [0]
com.esotericsoftware.kryo.KryoException: Unable to find class: ello! How are you?
Serialization trace:
tdate1 (com.app.AppProtocol$CustomMessage)
customMessages (com.app.AppProtocol$CustomChat)
chats (com.app.AppProtocol$CustomChatDataState)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:160)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:118)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:813)
        at com.romix.scala.serialization.kryo.ScalaCollectionSerializer.read(ScalaCollectionsSerializer.scala:45)
        at com.romix.scala.serialization.kryo.ScalaCollectionSerializer.read(ScalaCollectionsSerializer.scala:36)
        at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:731)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:125)
Caused by: java.lang.ClassNotFoundException: ello! How are you?
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readName(DefaultClassResolver.java:154)
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:133)
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:118)
        at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:540)
```
Above error appears if I add new field `tdate1` to my class. If I remove it, error disappears. 
My application.conf contains following lines:
```
akka {
  extensions = ["com.romix.akka.serialization.kryo.KryoSerializationExtension$"]

  actor {
    serializers {
      kryo = "com.romix.akka.serialization.kryo.KryoSerializer"
    }
    serialization-bindings {
      "java.io.Serializable" = kryo
    }
    kryo{
      type = "graph"
      idstrategy = "default"
      serializer-pool-size = 16
      buffer-size = 4096
      use-manifests = false
      implicit-registration-logging = true
      kryo-trace = false
    }
  }
}
```
I've following dependencies:
```
"com.typesafe.akka" %% "akka-persistence-cassandra" % "0.85",
"com.typesafe.akka" %% "akka-persistence-cassandra-launcher" % "0.85" % Test,
```
akka-kryo-serialization is version 0.5.2, akka version 2.5.13
How can I provide backward compatibility of classes with akka-persistence-cassandra?

**Comment by johanandren** [comment]
This is unrelated to cassandra and something _you_ must take care of in your application, having auto-generated serialization is in general problematic. Read the [Schema Evolution](https://doc.akka.io/docs/akka/current/persistence-schema-evolution.html#schema-evolution-in-event-sourced-systems) section of the Akka persistence docs carefully.

If you have further questions, please use the [forums](https://discuss.akka.io)
