### ISSUE TITLE
Failed: CassandraCorruptJournalSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#407]
```
[info] Cassandra recovery
[DEBUG] [10/15/2018 09:39:30.560] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-8] [CassandraJournal(akka://CassandraCorruptJournalSpec)] asyncReadHighestSequenceNr pid=1 0
[DEBUG] [10/15/2018 09:39:30.563] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-13] [CassandraJournal(akka://CassandraCorruptJournalSpec)] asyncReadHighestSequenceNr pid=1 0
[DEBUG] [10/15/2018 09:39:30.571] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-8] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovering pid pid=1 from 1 to 1
[DEBUG] [10/15/2018 09:39:30.582] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-8] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovery of pid [pid=1] sending tag progress: Map()
[DEBUG] [10/15/2018 09:39:30.583] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-8] [akka.serialization.Serialization(akka://CassandraCorruptJournalSpec)] Using serializer [akka.serialization.JavaSerializer] for message [akka.persistence.cassandra.journal.TagWriters$PidRecovering]
[DEBUG] [10/15/2018 09:39:30.583] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-9] [akka://CassandraCorruptJournalSpec/system/cassandra-journal/tagWrites] Recovering pid [pid=1] with progress [Map()]. Tags to reset as not in progress [Set()]
[DEBUG] [10/15/2018 09:39:30.585] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-12] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovery is starting before the latest tag writes tag progress. Min progress for pid 1. From sequence nr of recovery: 1
[DEBUG] [10/15/2018 09:39:30.585] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-12] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Starting recovery with tag progress: Map(). From 1 to 1
[DEBUG] [10/15/2018 09:39:30.585] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-12] [CassandraReadJournal] Creating EventByPersistentIdState graph
[DEBUG] [10/15/2018 09:39:30.587] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-9] [EventsByPersistenceIdStage(akka://CassandraCorruptJournalSpec)] EventsByPersistenceId [pid=1] Query from seqNr [1] in partition [0]
[DEBUG] [10/15/2018 09:39:30.590] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-9] [EventsByPersistenceIdStage(akka://CassandraCorruptJournalSpec)] EventsByPersistenceId [pid=1] Query took [3] ms 
[DEBUG] [10/15/2018 09:39:30.612] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-12] [CassandraJournal(akka://CassandraCorruptJournalSpec)] asyncReadHighestSequenceNr pid=1 0
[DEBUG] [10/15/2018 09:39:30.616] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovering pid pid=1 from 1 to 2
[DEBUG] [10/15/2018 09:39:30.621] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-13] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovery of pid [pid=1] sending tag progress: Map()
[DEBUG] [10/15/2018 09:39:30.622] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-13] [akka://CassandraCorruptJournalSpec/system/cassandra-journal/tagWrites] Recovering pid [pid=1] with progress [Map()]. Tags to reset as not in progress [Set()]
[DEBUG] [10/15/2018 09:39:30.622] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-13] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovery is starting before the latest tag writes tag progress. Min progress for pid 1. From sequence nr of recovery: 1
[DEBUG] [10/15/2018 09:39:30.622] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-13] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Starting recovery with tag progress: Map(). From 1 to 2
[DEBUG] [10/15/2018 09:39:30.622] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-13] [CassandraReadJournal] Creating EventByPersistentIdState graph
[DEBUG] [10/15/2018 09:39:30.626] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-9] [EventsByPersistenceIdStage(akka://CassandraCorruptJournalSpec)] EventsByPersistenceId [pid=1] Query from seqNr [1] in partition [0]
[DEBUG] [10/15/2018 09:39:30.628] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-9] [EventsByPersistenceIdStage(akka://CassandraCorruptJournalSpec)] EventsByPersistenceId [pid=1] Query took [1] ms 
[info] - must work with replay-filter = repair-by-discard-old *** FAILED *** (20 seconds, 87 milliseconds)
[info]   java.lang.AssertionError: timeout (20 seconds) waiting for 2 messages on WarningFilter(None,Right(Invalid replayed event),false)
[info]   at akka.testkit.EventFilter.intercept(TestEventListener.scala:114)
[info]   at akka.persistence.cassandra.CassandraCorruptJournalSpec.$anonfun$new$2(CassandraCorruptJournalSpec.scala:62)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$1.apply(WordSpecLike.scala:1078)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.persistence.cassandra.CassandraSpec.withFixture(CassandraSpec.scala:76)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1076)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1088)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1088)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1070)
[info]   at akka.persistence.cassandra.CassandraSpec.runTest(CassandraSpec.scala:76)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1147)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
[info]   at scala.collection.immutable.List.foreach(List.scala:389)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1147)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1146)
[info]   at akka.persistence.cassandra.CassandraSpec.runTests(CassandraSpec.scala:76)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at akka.persistence.cassandra.CassandraSpec.org$scalatest$WordSpecLike$$super$run(CassandraSpec.scala:76)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1192)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1192)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1190)
[info]   at akka.persistence.cassandra.CassandraSpec.org$scalatest$BeforeAndAfterAll$$super$run(CassandraSpec.scala:76)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.persistence.cassandra.CassandraSpec.run(CassandraSpec.scala:76)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:113)
[info]   at sbt.TestRunner.run(TestFramework.scala:124)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[info]   at sbt.TestFunction.apply(TestFramework.scala:294)
[info]   at sbt.Tests$.processRunnable$1(Tests.scala:347)
[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:67)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:278)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info]   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info]   at java.lang.Thread.run(Thread.java:748)
[DEBUG] [10/15/2018 09:39:50.658] [CassandraCorruptJournalSpec-akka.actor.default-dispatcher-5] [akka.persistence.Persistence(akka://CassandraCorruptJournalSpec)] Create plugin: cassandra-journal-fail akka.persistence.cassandra.journal.CassandraJournal
[DEBUG] [10/15/2018 09:39:50.662] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-17] [TimerScheduler(akka://CassandraCorruptJournalSpec)] Start timer [WriteTagScanningTick] with generation [1]
[DEBUG] [10/15/2018 09:39:50.672] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-11] [CassandraJournal(akka://CassandraCorruptJournalSpec)] asyncReadHighestSequenceNr pid=2 0
[DEBUG] [10/15/2018 09:39:50.674] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-19] [CassandraJournal(akka://CassandraCorruptJournalSpec)] asyncReadHighestSequenceNr pid=2 0
[DEBUG] [10/15/2018 09:39:50.759] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-19] [CassandraJournal(akka://CassandraCorruptJournalSpec)] asyncReadHighestSequenceNr pid=2 0
[DEBUG] [10/15/2018 09:39:50.762] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-11] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovering pid pid=2 from 1 to 2
[DEBUG] [10/15/2018 09:39:50.764] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovery of pid [pid=2] sending tag progress: Map()
[DEBUG] [10/15/2018 09:39:50.764] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-9] [akka://CassandraCorruptJournalSpec/system/cassandra-journal-fail/tagWrites] Recovering pid [pid=2] with progress [Map()]. Tags to reset as not in progress [Set()]
[DEBUG] [10/15/2018 09:39:50.765] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-19] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Recovery is starting before the latest tag writes tag progress. Min progress for pid 1. From sequence nr of recovery: 1
[DEBUG] [10/15/2018 09:39:50.765] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-19] [CassandraJournal(akka://CassandraCorruptJournalSpec)] Starting recovery with tag progress: Map(). From 1 to 2
[DEBUG] [10/15/2018 09:39:50.765] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-19] [CassandraReadJournal] Creating EventByPersistentIdState graph
[DEBUG] [10/15/2018 09:39:50.766] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-19] [EventsByPersistenceIdStage(akka://CassandraCorruptJournalSpec)] EventsByPersistenceId [pid=2] Query from seqNr [1] in partition [0]
[DEBUG] [10/15/2018 09:39:50.768] [CassandraCorruptJournalSpec-cassandra-plugin-default-dispatcher-19] [EventsByPersistenceIdStage(akka://CassandraCorruptJournalSpec)] EventsByPersistenceId [pid=2] Query took [1] ms 
[ERROR] [10/15/2018 09:39:50.770] [CassandraCorruptJournalSpec-akka.actor.default-dispatcher-15] [akka://CassandraCorruptJournalSpec/system/cassandra-journal-fail/$d] Invalid replayed event [sequenceNr=1, writerUUID=250c89b6-509b-4a71-8535-0dc26bc50a4f] from a new writer. An older writer already sent an event [sequenceNr=1, writerUUID=254e052a-51d0-4433-89d3-99a59ce506b8] whose sequence number was equal or greater for the same persistenceId [pid=2]. Perhaps, the new writer journaled the event out of sequence, or duplicate persistentId for different entities?
```

**Comment by chbatey** [comment]
https://travis-ci.org/akka/akka-persistence-cassandra/jobs/451489193

**Comment by chbatey** [comment]
Closing as we haven't seen this during  https://github.com/akka/akka-persistence-cassandra/pull/454 and the travis job has run 100s of times for that
