### ISSUE TITLE
Failed: CassandraDeletionSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#465]
On the branch for running against docker:

```
[info] Cassandra deletion
[ERROR] [05/14/2019 07:50:49.929] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-5] [akka://CassandraJournalDeletionSpec/user/$a] requirement failed: Received deletes in wrong order. Last 80. Current: 79
java.lang.IllegalArgumentException: requirement failed: Received deletes in wrong order. Last 80. Current: 79
	at scala.Predef$.require(Predef.scala:333)
	at akka.persistence.cassandra.journal.CassandraJournalDeletionSpec$PAThatDeletes$$anonfun$receiveCommand$1.applyOrElse(CassandraJournalDeletionSpec.scala:52)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.persistence.cassandra.journal.CassandraJournalDeletionSpec$PAThatDeletes.akka$persistence$Eventsourced$$super$aroundReceive(CassandraJournalDeletionSpec.scala:26)
	at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:753)
	at akka.persistence.Eventsourced.aroundReceive(Eventsourced.scala:222)
	at akka.persistence.Eventsourced.aroundReceive$(Eventsourced.scala:221)
	at akka.persistence.cassandra.journal.CassandraJournalDeletionSpec$PAThatDeletes.aroundReceive(CassandraJournalDeletionSpec.scala:26)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] - must allow concurrent deletes *** FAILED *** (625 milliseconds)
[info]   java.lang.AssertionError: assertion failed: expected Deleted(79), found Deleted(80)
[info]   at scala.Predef$.assert(Predef.scala:275)
[info]   at akka.testkit.TestKitBase.expectMsg_internal(TestKit.scala:403)
[info]   at akka.testkit.TestKitBase.expectMsg(TestKit.scala:379)
[info]   at akka.testkit.TestKitBase.expectMsg$(TestKit.scala:379)
[info]   at akka.testkit.TestKit.expectMsg(TestKit.scala:896)
[info]   at akka.persistence.cassandra.journal.CassandraJournalDeletionSpec.$anonfun$new$6(CassandraJournalDeletionSpec.scala:121)
[info]   at akka.persistence.cassandra.journal.CassandraJournalDeletionSpec.$anonfun$new$6$adapted(CassandraJournalDeletionSpec.scala:120)
[info]   at scala.collection.immutable.NumericRange.foreach(NumericRange.scala:86)
[info]   at akka.persistence.cassandra.journal.CassandraJournalDeletionSpec.$anonfun$new$2(CassandraJournalDeletionSpec.scala:120)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.persistence.cassandra.CassandraSpec.withFixture(CassandraSpec.scala:106)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:285)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[info]   at akka.persistence.cassandra.CassandraSpec.runTest(CassandraSpec.scala:76)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:392)
[info]   at scala.collection.immutable.List.foreach(List.scala:302)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:380)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:369)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:406)
[info]   at scala.collection.immutable.List.foreach(List.scala:302)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:380)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:375)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:457)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info]   at akka.persistence.cassandra.CassandraSpec.runTests(CassandraSpec.scala:76)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at akka.persistence.cassandra.CassandraSpec.org$scalatest$WordSpecLike$$super$run(CassandraSpec.scala:76)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:517)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[info]   at akka.persistence.cassandra.CassandraSpec.org$scalatest$BeforeAndAfterAll$$super$run(CassandraSpec.scala:76)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.persistence.cassandra.CassandraSpec.run(CassandraSpec.scala:76)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:113)
[info]   at sbt.TestRunner.run(TestFramework.scala:124)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[info]   at sbt.TestFunction.apply(TestFramework.scala:294)
[info]   at sbt.Tests$.processRunnable$1(Tests.scala:347)
[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:67)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:278)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] [05/14/2019 07:50:50.224] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.511] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.512] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.512] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.579] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.580] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.580] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.621] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-9] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.670] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(CassandraJournalDeletionSpec)] Failed to delete to 12
java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2
	at akka.persistence.cassandra.journal.CassandraJournal.asyncDeleteMessagesTo(CassandraJournal.scala:469)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$receiveWriteJournal$1.$anonfun$applyOrElse$21(AsyncWriteJournal.scala:161)
	at akka.pattern.CircuitBreaker$State.materialize$1(CircuitBreaker.scala:718)
	at akka.pattern.CircuitBreaker$State.callThrough(CircuitBreaker.scala:755)
	at akka.pattern.CircuitBreaker$State.callThrough$(CircuitBreaker.scala:716)
	at akka.pattern.CircuitBreaker$Closed$.callThrough(CircuitBreaker.scala:827)
	at akka.pattern.CircuitBreaker$Closed$.invoke(CircuitBreaker.scala:836)
	at akka.pattern.CircuitBreaker.withCircuitBreaker(CircuitBreaker.scala:232)
	at akka.persistence.journal.AsyncWriteJournal$$anonfun$receiveWriteJournal$1.applyOrElse(AsyncWriteJournal.scala:161)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.persistence.cassandra.journal.CassandraJournal.aroundReceive(CassandraJournal.scala:54)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[WARN] [05/14/2019 07:50:50.675] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-2] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,11)
[WARN] [05/14/2019 07:50:50.676] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-2] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,9)
[ERROR] [05/14/2019 07:50:50.677] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-10] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[WARN] [05/14/2019 07:50:50.708] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,14)
[WARN] [05/14/2019 07:50:50.708] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,10)
[WARN] [05/14/2019 07:50:50.708] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,15)
[ERROR] [05/14/2019 07:50:50.708] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-10] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.708] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-10] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.708] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-10] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.708] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-10] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[ERROR] [05/14/2019 07:50:50.718] [CassandraJournalDeletionSpec-cassandra-plugin-default-dispatcher-10] [CassandraJournal(akka://CassandraJournalDeletionSpec)] Over [5] outstanding deletes for persistenceId [p2]. Failing delete
[WARN] [05/14/2019 07:50:50.725] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,17)
[WARN] [05/14/2019 07:50:50.727] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,16)
[WARN] [05/14/2019 07:50:50.739] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,18)
[WARN] [05/14/2019 07:50:50.741] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,19)
[WARN] [05/14/2019 07:50:50.743] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,21)
[WARN] [05/14/2019 07:50:50.743] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,20)
[WARN] [05/14/2019 07:50:50.746] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(java.lang.RuntimeException: Over 5 outstanding deletes for persistenceId p2,22)
[WARN] [05/14/2019 07:50:50.750] [CassandraJournalDeletionSpec-akka.actor.default-dispatcher-14] [akka://CassandraJournalDeletionSpec/user/$b] received dead letter from Actor[akka://CassandraJournalDeletionSpec/system/cassandra-journal-low-concurrent-deletes#1487342928]: DeleteMessagesFailure(akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast,25)
```

**Comment by chbatey** [comment]
This test expects to receive the `DeleteSuccess` in the same order the CassandraJournal completes them. This isn't guaranteed by the AsyncWriteJournal as it sends the message from a future callback. This test needs relaxed

**Comment by chbatey** [comment]
Fixed by https://github.com/akka/akka-persistence-cassandra/pull/454
