### ISSUE TITLE
Failed: EventsByTagZeroEventualConsistencyDelaySpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#466]
On the branch for running against docker this could be a test problem that for some reason happens more frequently with an external Cassandra.

The test persists many events and then starts a current events by tag query. The tests failure does not indicate which event wasn't found as it is an expectMsg in a loop. I'll add some logs to see if this is either a bug or that the offset that the currentEventsByTag is going from/to doesn't include the events for some reason.

```
[0m[[0m[0minfo[0m] [0m[0m[32mEventsByTagZeroEventualConsistencyDelaySpec:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32mCassandra query currentEventsByTag with zero eventual-consistency-delay[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m- must find existing events *** FAILED *** (30 seconds, 617 milliseconds)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  java.lang.AssertionError: assertion failed: timeout (20 seconds) during expectMsg: message matching partial function[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at scala.Predef$.assert(Predef.scala:275)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.expectMsgPF(TestKit.scala:420)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKitBase.expectMsgPF$(TestKit.scala:417)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.testkit.TestKit.expectMsgPF(TestKit.scala:896)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.stream.testkit.TestSubscriber$ManualProbe.expectEventWithTimeoutPF(StreamTestKit.scala:649)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextWithTimeoutPF(StreamTestKit.scala:626)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.stream.testkit.TestSubscriber$ManualProbe.expectNextPF(StreamTestKit.scala:618)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.persistence.cassandra.query.EventsByTagZeroEventualConsistencyDelaySpec.$anonfun$new$25(EventsByTagSpec.scala:519)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:22)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Transformer.apply(Transformer.scala:20)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.persistence.cassandra.CassandraSpec.withFixture(CassandraSpec.scala:106)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:285)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.persistence.cassandra.query.AbstractEventsByTagSpec.org$scalatest$BeforeAndAfterEach$$super$runTest(EventsByTagSpec.scala:118)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:221)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.persistence.cassandra.query.AbstractEventsByTagSpec.runTest(EventsByTagSpec.scala:118)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:392)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.List.foreach(List.scala:302)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:380)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:369)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:406)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at scala.collection.immutable.List.foreach(List.scala:302)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:380)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:375)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:457)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.persistence.cassandra.CassandraSpec.runTests(CassandraSpec.scala:76)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Suite.run(Suite.scala:1147)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.Suite.run$(Suite.scala:1129)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.persistence.cassandra.CassandraSpec.org$scalatest$WordSpecLike$$super$run(CassandraSpec.scala:76)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.SuperEngine.runImpl(Engine.scala:517)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.persistence.cassandra.CassandraSpec.org$scalatest$BeforeAndAfterAll$$super$run(CassandraSpec.scala:76)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at akka.persistence.cassandra.CassandraSpec.run(CassandraSpec.scala:76)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.TestRunner.runTest$1(TestFramework.scala:113)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.TestRunner.run(TestFramework.scala:124)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.TestFunction.apply(TestFramework.scala:294)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.Tests$.processRunnable$1(Tests.scala:347)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.std.Transform$$anon$4.work(System.scala:67)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.Execute.$anonfun$submit$2(Execute.scala:269)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.Execute.work(Execute.scala:278)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.Execute.$anonfun$submit$1(Execute.scala:269)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at java.base/java.lang.Thread.run(Thread.java:834)[0m[0m
RowDump::
Row:banana,1557792000000,165c9980-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:784),a,1,2
Row:banana,1557792000000,165d5cd0-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:789),a,2,3
Row:banana,1557792000000,165daaf0-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:791),a,3,4
Row:banana,1557792000000,165df910-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:793),a,4,5
Row:banana,1557792000000,165e2020-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:794),a,5,6
Row:banana,1557792000000,165e6e40-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:796),a,6,7
Row:banana,1557792000000,165e9550-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:797),a,7,8
Row:banana,1557792000000,165ee370-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:799),a,8,9
Row:banana,1557792000000,165f0a80-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:800),a,9,10
Row:banana,1557792000000,165f3190-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:801),a,10,11
Row:banana,1557792000000,165f7fb0-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:803),a,11,12
Row:banana,1557792000000,165fa6c0-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:804),a,12,13
Row:banana,1557792000000,165fcdd0-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:805),a,13,14
Row:banana,1557792000000,16601bf0-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:807),a,14,15
Row:banana,1557792000000,16606a10-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:809),a,15,16
Row:banana,1557792000000,1660df40-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:812),a,16,17
Row:banana,1557792000000,16612d60-761c-11e9-a395-49138a988021 (2019-05-14 07:44:21:814),a,17,18
```

**Comment by chbatey** [comment]
Fixed by https://github.com/akka/akka-persistence-cassandra/pull/454
