### ISSUE TITLE
Failed: CassandraLoadTypedSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#469]
Full logs in case travis GCs the logs

```
[info] CassandraLoadTypedSpec:
Starting Cassandra on port client port: 33944 storage port 41462 host 127.0.0.1 java version 11+28
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.cassandra.utils.FBUtilities (file:/home/travis/build/akka/akka-persistence-cassandra/target/CassandraLoadTypedSpec/cassandra-bundle.jar) to field java.io.FileDescriptor.fd
WARNING: Please consider reporting this to the maintainers of org.apache.cassandra.utils.FBUtilities
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
05/14 10:00:11 ERROR[main] o.a.c.s.StartupChecks - cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
[info] Typed EventSourcedBehavior with Cassandra journal
[info] - should have some reasonable write throughput *** FAILED *** (3 seconds, 671 milliseconds)
[info]   java.lang.AssertionError: Timeout (3 seconds) during expectMessageClass waiting for class java.lang.String
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.assertFail(TestProbeImpl.scala:305)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageClass_internal(TestProbeImpl.scala:203)
[info]   at akka.actor.testkit.typed.scaladsl.TestProbe.expectMessageType(TestProbe.scala:146)
[info]   at akka.actor.testkit.typed.scaladsl.TestProbe.expectMessageType$(TestProbe.scala:145)
[info]   at akka.actor.testkit.typed.internal.TestProbeImpl.expectMessageType(TestProbeImpl.scala:53)
[info]   at akka.persistence.cassandra.journal.CassandraLoadTypedSpec.testThroughput(CassandraLoadTypedSpec.scala:147)
[info]   at akka.persistence.cassandra.journal.CassandraLoadTypedSpec.$anonfun$new$3(CassandraLoadTypedSpec.scala:182)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:161)
[info]   at akka.persistence.cassandra.journal.CassandraLoadTypedSpec.$anonfun$new$2(CassandraLoadTypedSpec.scala:181)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at akka.persistence.cassandra.CassandraSpec.withFixture(CassandraSpec.scala:76)
[info]   at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info]   at org.scalatest.SuperEngine.runTestImpl(Engine.scala:285)
[info]   at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info]   at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[info]   at akka.persistence.cassandra.CassandraSpec.runTest(CassandraSpec.scala:76)
[info]   at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:392)
[info]   at scala.collection.immutable.List.foreach(List.scala:302)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:380)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:369)
[info]   at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:406)
[info]   at scala.collection.immutable.List.foreach(List.scala:302)
[info]   at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:380)
[info]   at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:375)
[info]   at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:457)
[info]   at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info]   at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info]   at akka.persistence.cassandra.CassandraSpec.runTests(CassandraSpec.scala:76)
[info]   at org.scalatest.Suite.run(Suite.scala:1147)
[info]   at org.scalatest.Suite.run$(Suite.scala:1129)
[info]   at akka.persistence.cassandra.CassandraSpec.org$scalatest$WordSpecLike$$super$run(CassandraSpec.scala:76)
[info]   at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[info]   at org.scalatest.SuperEngine.runImpl(Engine.scala:517)
[info]   at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[info]   at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[info]   at akka.persistence.cassandra.CassandraSpec.org$scalatest$BeforeAndAfterAll$$super$run(CassandraSpec.scala:76)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at akka.persistence.cassandra.CassandraSpec.run(CassandraSpec.scala:76)
[info]   at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:113)
[info]   at sbt.TestRunner.run(TestFramework.scala:124)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.$anonfun$apply$1(TestFramework.scala:282)
[info]   at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:246)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[info]   at sbt.TestFramework$$anon$2$$anonfun$$lessinit$greater$1.apply(TestFramework.scala:282)
[info]   at sbt.TestFunction.apply(TestFramework.scala:294)
[info]   at sbt.Tests$.processRunnable$1(Tests.scala:347)
[info]   at sbt.Tests$.$anonfun$makeSerial$1(Tests.scala:353)
[info]   at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:46)
[info]   at sbt.std.Transform$$anon$4.work(System.scala:67)
[info]   at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[info]   at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[info]   at sbt.Execute.work(Execute.scala:278)
[info]   at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[info]   at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[info]   at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[info]   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]   at java.base/java.lang.Thread.run(Thread.java:834)
[info] - should work properly under load (1 second, 410 milliseconds)
```

https://travis-ci.org/akka/akka-persistence-cassandra/jobs/532204462

**Comment by ennru** [comment]
https://travis-ci.org/akka/akka-persistence-cassandra/jobs/658198026#L1397 in #717

**Comment by ennru** [comment]
https://travis-ci.org/akka/akka-persistence-cassandra/jobs/658591831#L5610

**Comment by ennru** [comment]
https://travis-ci.org/akka/akka-persistence-cassandra/jobs/658591832#L5632

**Comment by ignasi35** [comment]
https://travis-ci.com/github/akka/akka-persistence-cassandra/jobs/499410468#L7388
