### ISSUE TITLE
Saving snapshot failes with large snapshot (> 16 MB)

### ISSUE THREAD

**Issue by lukas-phaf** [akka/akka-persistence-cassandra#543]
I am using akka-persistence-cassandra to persist the snapshots of a PersistentActor. When I try to persist a large snapshot (> 16 MB in this case), I get the following in the logs of my Akka application:

```
[INFO] 2019-08-20 08:39:48,450  346460  - Retrying on request error on next host at consistency ONE (initial consistency: ONE, retries: 0, exception: com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 3 failed))
[INFO] 2019-08-20 08:39:49,971  347981  - Retrying on request error on next host at consistency ONE (initial consistency: ONE, retries: 1, exception: com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 3 failed))
[INFO] 2019-08-20 08:39:51,570  349580  - Retrying on request error on next host at consistency ONE (initial consistency: ONE, retries: 2, exception: com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 3 failed))
```
In the PersistentActor, I receive a SaveSnapshotFailure with the following cause:
```
com.datastax.driver.core.exceptions.WriteFailureException: Cassandra failure during write query at consistency ONE (1 responses were required but only 0 replica responded, 3 failed)
```
In the Cassandra logs I see errors like below:
```
ERROR [MutationStage-2] 2019-08-20 08:39:47,352 StorageProxy.java:1404 - Failed to apply mutation locally : {}
java.lang.IllegalArgumentException: Mutation of 56.534MiB is too large for the maximum size of 16.000MiB
	at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:245) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:593) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Keyspace.apply(Keyspace.java:470) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:227) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:232) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Mutation.apply(Mutation.java:241) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.StorageProxy$8.runMayThrow(StorageProxy.java:1398) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.service.StorageProxy$LocalMutationRunnable.run(StorageProxy.java:2637) [apache-cassandra-3.11.4.jar:3.11.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:114) [apache-cassandra-3.11.4.jar:3.11.4]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
WARN  [MutationStage-1] 2019-08-20 08:39:49,957 AbstractLocalAwareExecutorService.java:167 - Uncaught exception on thread Thread[MutationStage-1,5,main]: {}
java.lang.IllegalArgumentException: Mutation of 56.534MiB is too large for the maximum size of 16.000MiB
	at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:245) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:593) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Keyspace.applyFuture(Keyspace.java:433) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:222) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.MutationVerbHandler.doVerb(MutationVerbHandler.java:68) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:114) [apache-cassandra-3.11.4.jar:3.11.4]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
WARN  [MutationStage-1] 2019-08-20 08:39:51,505 AbstractLocalAwareExecutorService.java:167 - Uncaught exception on thread Thread[MutationStage-1,5,main]: {}
java.lang.IllegalArgumentException: Mutation of 56.534MiB is too large for the maximum size of 16.000MiB
	at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:245) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:593) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Keyspace.applyFuture(Keyspace.java:433) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:222) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.MutationVerbHandler.doVerb(MutationVerbHandler.java:68) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:114) [apache-cassandra-3.11.4.jar:3.11.4]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
WARN  [MutationStage-1] 2019-08-20 08:39:53,142 AbstractLocalAwareExecutorService.java:167 - Uncaught exception on thread Thread[MutationStage-1,5,main]: {}
java.lang.IllegalArgumentException: Mutation of 56.534MiB is too large for the maximum size of 16.000MiB
	at org.apache.cassandra.db.commitlog.CommitLog.add(CommitLog.java:245) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Keyspace.applyInternal(Keyspace.java:593) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Keyspace.applyFuture(Keyspace.java:433) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.Mutation.applyFuture(Mutation.java:222) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.db.MutationVerbHandler.doVerb(MutationVerbHandler.java:68) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.net.MessageDeliveryTask.run(MessageDeliveryTask.java:66) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$FutureTask.run(AbstractLocalAwareExecutorService.java:162) ~[apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.concurrent.AbstractLocalAwareExecutorService$LocalSessionFutureTask.run(AbstractLocalAwareExecutorService.java:134) [apache-cassandra-3.11.4.jar:3.11.4]
	at org.apache.cassandra.concurrent.SEPWorker.run(SEPWorker.java:114) [apache-cassandra-3.11.4.jar:3.11.4]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
```

I confirmed that the snapshot is indeed not written to Cassandra.

Should akka-persistence-cassandra be able to handle snapshots of arbitrary size, or is this an limitation that I will have to live with?

### Versions used 

Akka version: 2.5.23
akka-persistence-cassandra version: 0.99
Cassanra version: 3.11.4

### Expected Behavior

The snapshot should get persisted into Cassandra, without any errors.

### Actual Behavior

See description above.

### Relevant logs

See description above.

**Comment by johanandren** [comment]
That's a Cassandra configuration issue, not a problem with the akka-persistence-cassandra.

https://support.datastax.com/hc/en-us/articles/207267063-Mutation-of-x-bytes-is-too-large-for-the-maxiumum-size-of-y-

**Comment by lukas-phaf** [comment]
@johanandren, thanks for the quick reply. I did see that article when I searched for the Cassandra error (I should have mentioned that). 

There are several reasons that I don't want to go that way:
1. I think this is a global setting, and I assume there are performance implications to changing it.
2. What should I set it to, as it is not clear upfront how big the snapshots can become.
3. The Cassandra instance we use is shared, and I don't want to change this for all users.

Although 16 MB of state in a single actor is large, I don't think this is excessive.

Maybe this should not be a bug report, but a feature request to support snapshots of arbitrary size?

**Comment by patriknw** [comment]
What do you suggest? That it would split up the snapshot bytes and save them separately, then reassemble again when loading. I don't think we will work on such feature, and I'm not even sure we would accept a contribution of it since it would be pretty complicated for a limited/questionable use case.

I suggest that you look into if you can change the Cassandra server config.

**Comment by lukas-phaf** [comment]
@patriknw, thanks for clarifying that. 
That is indeed what I had in mind. If this is a no go, I'll look into getting the snapshot size down, or moving the state over multiple actors.

Can you add this limitation to the documentation, as it is an arbitrary limitation of this particular persistence back-end?

**Comment by patriknw** [comment]
ok, we'll add something to docs.
For reference: http://cassandra.apache.org/doc/latest/faq/index.html#can-large-blob

**Comment by lukas-phaf** [comment]
Thanks.
