### ISSUE TITLE
Docs publish in release-0.x branch does not work

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#636]
For 0.102 I had to do it locally.

It worked last time for 0.101.

This time it gets:

```
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
Warning: Permanently added 'gustav.akka.io,54.87.253.56' (ECDSA) to the list of known hosts.
Permission denied (publickey).
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.0]
[error] java.lang.IllegalStateException: rsync command exited with an error code 255
[error] 	at com.lightbend.sbt.publishrsync.PublishRsyncPlugin$.$anonfun$publishRsyncSettings$1(PublishRsyncPlugin.scala:42)
[error] 	at com.lightbend.sbt.publishrsync.PublishRsyncPlugin$.$anonfun$publishRsyncSettings$1$adapted(PublishRsyncPlugin.scala:36)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u
```

To fix the docs i checked out the v0.102 tag and ran:

```
sbt  docs/publishRsync
```

**Comment by chbatey** [comment]
This was an issue with authorized keys on the docs server. I've fixed it and verified. Should work for the next relesae
