### ISSUE TITLE
Type mismatch at akka clustering PersistentShardCoordinator during deserialization

### ISSUE THREAD

**Issue by stascode** [akka/akka-persistence-cassandra#64]
Steps to repro: 
1. Use both akka-cluster-sharding and akka-persistence-cassandra in the project 
2. Initialize clustered system by invoking ClusterSharding(system).start(...,typeName="MyClusteredSystem",...). 
3. Run the app
4. Stop/kill the app after a while
5. Run the app again - exception is thrown:

[ERROR] akka.cluster.sharding.PersistentShardCoordinator! Persistence failure when replaying events for persistenceId [/sharding/MyClusteredSystemCoordinator]. Last known sequence number [1]
java.lang.ClassCastException: scala.runtime.BoxedUnit cannot be cast to akka.Done
	at akka.persistence.cassandra.journal.CassandraRecovery$$anonfun$asyncReplayMessages$1.apply(CassandraRecovery.scala:48) ~[akka-persistence-cassandra_2.11-0.10.jar:0.10]
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.util.Success.map(Try.scala:237) ~[scala-library-2.11.7.jar:1.0.0-M1]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91) ~[akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[akka-actor_2.11-2.4.2.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405) ~[akka-actor_2.11-2.4.2.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]

**Comment by patriknw** [comment]
That looks like a critical issue, but I wonder why we have not seen it anywhere else. I'm also puzzled by the exception, "scala.runtime.BoxedUnit cannot be cast to akka.Done" at 
https://github.com/akka/akka-persistence-cassandra/blob/v0.10/src/main/scala/akka/persistence/cassandra/journal/CassandraRecovery.scala#L48

Can you please double check what version of akka-stream that you in your classpath? It should be akka-stream_2.11-2.4.2.jar

**Comment by stascode** [comment]
Thanks for the hint! Somehow I was mislead in referencing akka-stream-experimental_2.11-2.0.3. Updated to akka_stream_2.11-2.4.2 and the issue is gone!

**Comment by patriknw** [comment]
yes, that explains it
