### ISSUE TITLE
Failed: EventsByTagPersistenceIdCleanupSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-persistence-cassandra#652]
https://travis-ci.org/akka/akka-persistence-cassandra/jobs/639522810?utm_medium=notification&utm_source=email

```
info] - must drop state and trigger new persistence id lookup peridodically *** FAILED *** (1 second, 826 milliseconds)
[info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(ca7f43e0-3b97-11ea-8da9-ff25a5303a6c),cleanup,2,cleanup-2)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis
[info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:726)
[info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:690)
[info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:689)
[info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:928)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMessage(StreamTestKit.scala:644)
[info]   at akka.persistence.cassandra.query.EventsByTagPersistenceIdCleanupSpec.$anonfun$new$102(EventsByTagSpec.scala:1342)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
```

Rows:

```
RowDump::
tag_views
Row:cleanup-tag,1579305600000,74c53470-3a05-11ea-8da9-ff25a5303a6c (2020-01-18 15:16:09:655),cleanup,1,1
Row:cleanup-tag,1579478400000,ca7f43e0-3b97-11ea-8da9-ff25a5303a6c (2020-01-20 15:16:11:166),cleanup,2,2
messages
```

Logs

```
--> [PersistenceId cleanup must drop state and trigger new persistence id lookup peridodically] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(ca7f43e0-3b97-11ea-8da9-ff25a5303a6c),cleanup,2,cleanup-2)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis)]
| [INFO] [01/20/2020 15:16:09.900] [EventsByTagPersistenceIdCleanupSpec-akka.actor.default-dispatcher-6] [EventsByTagStage(akka://EventsByTagPersistenceIdCleanupSpec)] [cf1fe549-8886-40a3-a5e7-1bfb929a2c11]: EventsByTag query [cleanup-tag] starting with EC delay 0ms: fromOffset [74c50d60-3a05-11ea-8080-808080808080 (2020-01-18 15:16:09:654)] toOffset [None]
<-- [PersistenceId cleanup must drop state and trigger new persistence id lookup peridodically] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(ca7f43e0-3b97-11ea-8da9-ff25a5303a6c),cleanup,2,cleanup-2)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis)]
```

**Comment by patriknw** [comment]
another https://travis-ci.org/akka/akka-persistence-cassandra/jobs/649884898

**Comment by patriknw** [comment]
https://travis-ci.org/github/akka/akka-persistence-cassandra/jobs/663458115

**Comment by patriknw** [comment]
https://travis-ci.org/github/akka/akka-persistence-cassandra/jobs/666681457

**Comment by patriknw** [comment]
https://travis-ci.org/github/akka/akka-persistence-cassandra/jobs/674898572
```
--> [PersistenceId cleanup must drop state and trigger new persistence id lookup peridodically] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(d4d6e790-7e62-11ea-8252-772073311428),cleanup,2,cleanup-2,1586877353097)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis)]
1404| [INFO] [04/14/2020 15:15:51.832] [EventsByTagPersistenceIdCleanupSpec-akka.actor.default-dispatcher-8] [EventsByTagStage(akka://EventsByTagPersistenceIdCleanupSpec)] [0038f21a-38af-4626-a3dc-6e2b777c050d]: EventsByTag query [cleanup-tag] starting with EC delay 0ms: fromOffset [7f298250-7cd0-11ea-8080-808080808080 (2020-04-12 15:15:51:669)] toOffset [None]
1405<-- [PersistenceId cleanup must drop state and trigger new persistence id lookup peridodically] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(d4d6e790-7e62-11ea-8252-772073311428),cleanup,2,cleanup-2,1586877353097)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis)]
1406[info] - must drop state and trigger new persistence id lookup peridodically *** FAILED *** (1 second, 737 milliseconds)
1407[info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(d4d6e790-7e62-11ea-8252-772073311428),cleanup,2,cleanup-2,1586877353097)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis
1408[info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:727)
1409[info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:691)
1410[info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:690)
1411[info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:929)
1412[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMessage(StreamTestKit.scala:644)
1413[info]   at akka.persistence.cassandra.query.EventsByTagPersistenceIdCleanupSpec.$anonfun$new$104(EventsByTagSpec.scala:1385)
```

**Comment by johanandren** [comment]
https://travis-ci.org/github/akka/akka-persistence-cassandra/jobs/712616719

```
--> [PersistenceId cleanup must drop state and trigger new persistence id lookup peridodically] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(c226bf80-d0ec-11ea-b352-0959596fc699),cleanup,2,cleanup-2,1595952587640)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis)]
784| [INFO] [07/28/2020 16:09:46.373] [EventsByTagPersistenceIdCleanupSpec-akka.actor.default-dispatcher-7] [EventsByTagStage(akka://EventsByTagPersistenceIdCleanupSpec)] [9dc1fd87-a690-446d-8b46-fc3a24252d9d]: EventsByTag query [cleanup-tag] starting with EC delay 0ms: fromOffset [6c8f0520-cf5a-11ea-8080-808080808080 (2020-07-26 16:09:46:354)] toOffset [None]
785<-- [PersistenceId cleanup must drop state and trigger new persistence id lookup peridodically] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(c226bf80-d0ec-11ea-b352-0959596fc699),cleanup,2,cleanup-2,1595952587640)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis)]
786[info] - must drop state and trigger new persistence id lookup peridodically *** FAILED *** (1 second, 596 milliseconds)
787[info]   java.lang.AssertionError: assertion failed: received unexpected message RealMessage(OnNext(EventEnvelope(TimeBasedUUID(c226bf80-d0ec-11ea-b352-0959596fc699),cleanup,2,cleanup-2,1595952587640)),Actor[akka://EventsByTagPersistenceIdCleanupSpec/deadLetters]) after 300 millis
788[info]   at akka.testkit.TestKitBase.expectNoMsg_internal(TestKit.scala:727)
789[info]   at akka.testkit.TestKitBase.expectNoMessage(TestKit.scala:691)
790[info]   at akka.testkit.TestKitBase.expectNoMessage$(TestKit.scala:690)
791[info]   at akka.testkit.TestKit.expectNoMessage(TestKit.scala:929)
792[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNoMessage(StreamTestKit.scala:644)
793[info]   at akka.persistence.cassandra.query.EventsByTagPersistenceIdCleanupSpec.$anonfun$new$104(EventsByTagSpec.scala:1386)
```

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-cassandra/actions/runs/5200381037/jobs/9379017664#step:6:666

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-cassandra/actions/runs/5424582339/jobs/9864143176#step:6:634

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-cassandra/actions/runs/6743977942/job/18332909422#step:6:607

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-cassandra/actions/runs/6743977942/job/18332910466#step:6:613

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-cassandra/actions/runs/8773074361/job/24072733919?pr=1093#step:6:599

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-cassandra/actions/runs/9643540096/job/26593753716?pr=1104

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-cassandra/actions/runs/13327120575/job/37222756573#step:6:724

**Comment by johanandren** [comment]
https://github.com/akka/akka-persistence-cassandra/actions/runs/14832538199/job/41636668233#step:6:791
