### ISSUE TITLE
`sbt +publishLocal` failure

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-persistence-cassandra#703]
Using `sbt + publishLocal` on the `release-0.x` branch fails:

```
...

[info] :: delivering :: com.typesafe.akka#akka-persistence-cassandra_2.11;0.103-SNAPSHOT :: 0.103-SNAPSHOT :: integration :: Fri Feb 21 15:45:16 CET 2020
[info]  delivering ivy file to /Users/ignasi/git/github/akka/akka-persistence-cassandra/master/core/target/ivy-0.103-SNAPSHOT.xml
[info]  published akka-persistence-cassandra_2.11 to /Users/ignasi/.ivy2/local/com.typesafe.akka/akka-persistence-cassandra_2.11/0.103-SNAPSHOT/poms/akka-persistence-cassandra_2.11.pom
[info]  published akka-persistence-cassandra_2.11 to /Users/ignasi/.ivy2/local/com.typesafe.akka/akka-persistence-cassandra_2.11/0.103-SNAPSHOT/bundles/akka-persistence-cassandra_2.11.jar
[info]  published akka-persistence-cassandra_2.11 to /Users/ignasi/.ivy2/local/com.typesafe.akka/akka-persistence-cassandra_2.11/0.103-SNAPSHOT/srcs/akka-persistence-cassandra_2.11-sources.jar
[info]  published akka-persistence-cassandra_2.11 to /Users/ignasi/.ivy2/local/com.typesafe.akka/akka-persistence-cassandra_2.11/0.103-SNAPSHOT/docs/akka-persistence-cassandra_2.11-javadoc.jar
[info]  published ivy to /Users/ignasi/.ivy2/local/com.typesafe.akka/akka-persistence-cassandra_2.11/0.103-SNAPSHOT/ivys/ivy.xml
[error] java.lang.IllegalStateException: Ivy file not found in cache for com.typesafe.akka#akka-persistence-cassandra-root_2.11;0.103-SNAPSHOT!
[error]         at sbt.internal.librarymanagement.ResolutionCache.getResolvedModuleDescriptor(ResolutionCache.scala:66)
[error]         at org.apache.ivy.core.deliver.DeliverEngine.deliver(DeliverEngine.java:111)
[error]         at org.apache.ivy.Ivy.deliver(Ivy.java:601)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$deliver$2(IvyActions.scala:100)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error]         at sbt.internal.librarymanagement.IvyActions$.deliver(IvyActions.scala:95)
[error]         at sbt.internal.librarymanagement.IvyActions$.publish(IvyActions.scala:129)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4(Defaults.scala:2416)
[error]         at sbt.Classpaths$.$anonfun$publishTask$4$adapted(Defaults.scala:2416)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (publishLocal) java.lang.IllegalStateException: Ivy file not found in cache for com.typesafe.akka#akka-persistence-cassandra-root_2.11;0.103-SNAPSHOT!
[error] Total time: 28 s, completed Feb 21, 2020 3:45:18 PM
sbt:akka-persistence-cassandra-root>
```

**Comment by ignasi35** [comment]
Apparently this can sometimes happen because of an internal issue in the Ivy publishing internals. 

There's a workaround: use `sbt +update` first and `sbt +publishLocal` should work as expected.

**Comment by patriknw** [comment]
thanks for recording the solution
