### ISSUE TITLE
failed: EventsByTagSpec NoSuchElementException cluster.getMetadata.getKeyspace

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#768]
Test failed in https://github.com/akka/akka-persistence-cassandra/pull/763

```
[info] - must set ttl on table *** FAILED *** (10 milliseconds)
2739[info]   java.util.NoSuchElementException: No value present
2740[info]   at java.base/java.util.Optional.get(Optional.java:148)
2741[info]   at akka.persistence.cassandra.query.EventsByTagSpec.$anonfun$new$2(EventsByTagSpec.scala:185)
```

Some kind of initialization order? keyspace or table not fully created at that point?

**Comment by patriknw** [comment]
I think I solved this by adding a `refreshSchema()`
