### ISSUE TITLE
failed: MultiPluginSpec

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-cassandra#770]
Failed in https://github.com/akka/akka-persistence-cassandra/pull/763

```
[info] A Cassandra snapshot store
4743--> [A Cassandra snapshot store must be usable multiple times with different configurations for two actors having the same persistence id] Start of log messages of test that [Failed(java.lang.AssertionError: assertion failed: not found [msg-1] found unexpected [msg-2])]
4744<-- [A Cassandra snapshot store must be usable multiple times with different configurations for two actors having the same persistence id] End of log messages of test that [Failed(java.lang.AssertionError: assertion failed: not found [msg-1] found unexpected [msg-2])]
4745[info] - must be usable multiple times with different configurations for two actors having the same persistence id *** FAILED *** (53 milliseconds)
4746[info]   java.lang.AssertionError: assertion failed: not found [msg-1] found unexpected [msg-2]
4747[info]   at scala.Predef$.assert(Predef.scala:282)
4748[info]   at akka.testkit.TestKitBase.checkMissingAndUnexpected(TestKit.scala:604)
4749[info]   at akka.testkit.TestKitBase.expectMsgAllOf_internal(TestKit.scala:612)
4750[info]   at akka.testkit.TestKitBase.expectMsgAllOf(TestKit.scala:580)
4751[info]   at akka.testkit.TestKitBase.expectMsgAllOf$(TestKit.scala:580)
4752[info]   at akka.persistence.cassandra.CassandraSpec.expectMsgAllOf(CassandraSpec.scala:92)
4753[info]   at akka.persistence.cassandra.journal.MultiPluginSpec.$anonfun$new$4(MultiPluginSpec.scala:126)
```

**Comment by patriknw** [comment]
fixed in that PR
