### ISSUE TITLE
persistAll fails for larger number of events

### ISSUE THREAD

**Issue by nvollmar** [akka/akka-persistence-cassandra#869]
### Versions used 
Akka version: 2.6.13
Akka Persistence Cassandra version: 1.0.4

### Expected Behavior
It should persist all events

### Actual Behavior
Fails persisting the first event

### Relevant logs
```
 09:24:10.888 ERROR Swpvemvcz9m|j.c.a.b.s.r.AggregateBackupRestoreWorker|akka://Swpvemvcz9m/user/backup-service/worker/aggregateRestore/restoreworker-realm-scopes.testing-testBackup-8aca5c52-a4a0-4174-8335-70c0607a8454|Swpvemvcz9m-jaso.backup.backupdispatcher-15 Failed to persist event type [AggregateBackupRestoreWorker$EvtBackupNoOp] with sequence number [1] for persistenceId [testBackup-8aca5c52-a4a0-4174-8335-70c0607a8454].
 java.util.NoSuchElementException: head of empty list
	at scala.collection.immutable.Nil$.head(List.scala:629)
	at scala.collection.immutable.Nil$.head(List.scala:628)
	at akka.persistence.cassandra.journal.CassandraJournal.writeMessages(CassandraJournal.scala:358)
	at akka.persistence.cassandra.journal.CassandraJournal.rec$1(CassandraJournal.scala:276)
	at akka.persistence.cassandra.journal.CassandraJournal.$anonfun$asyncWriteMessages$8(CassandraJournal.scala:276)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:434)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:53)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
```

### Reproducible Test Case
A `PersistentActor` with a new `persistenceId`
```
    case m: InitializeSequenceNrTo =>
      log.info("Persisting and deleting no-op events to initialize current aggregate sequenceNr to {}", m.nrOfDeletedEvents.nonCid)
      persistAll(List.tabulate(m.nrOfDeletedEvents)(nr => EvtBackupNoOp(nr + 1))){ _ => }
```
It works for `nrOfDeletedEvents = 100`, but fails for `nrOfDeletedEvents = 200`

**Comment by patriknw** [comment]
@nvollmar thanks for reporting, fix in https://github.com/akka/akka-persistence-cassandra/pull/873

**Comment by nvollmar** [comment]
@patriknw Just noticed this is a duplicate of #860
